#!/bin/sh
#
# page - A simple password manager using age written in POSIX sh.
#
# Copyright (C) 2020-2022 - Dylan Araps <dylan.araps@gmail.com>,
#                           Ricardo García Jiménez <ricardogj08@riseup.net>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this software except in compliance with the License.
# You may obtain a copy of the License at:
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Muestra mensajes de errores.
#
errors() {
  printf '%s.\n' "$1" >&2
  exit 1
}

#
# Muestra un mensaje de ayuda.
#
shelp() { printf '%s' "\
page 1.0 - A simple password manager using age written in POSIX sh.

Synopsis:
  page [OPTION]

Options:
  -a <NAME> - Add a new password.
  -c <NAME> - Copy a password to the clipboard.
  -d <NAME> - Delete a password.
  -g        - Generate a master key.
  -l        - List all password names.
  -s <NAME> - Show a password.

Environment vars:
  - Storage location:  export PAGE_DIR=~/.local/share/page
  - Password length:   export PAGE_LENGTH=12
  - Password pattern:  export PAGE_PATTERN=_[:alnum:]
  - Clipboard tool:    export PAGE_CLIPBOARD='waycopy -s seat0 -t text/plain'
  - Clipboard timeout: export PAGE_TIMEOUT=15
"
exit 0
}

#
# Valida si un string coincide con un patrón de búsqueda.
#
# @return boolean
#
# shellcheck disable=SC2254
#
match() { case $1 in $2) return 0; esac; return 1; }

#
# Genera una llave maestra de cifrado.
#
gen_key() {
  [ -f "$key" ] &&
    errors "Master key already exists"

  age-keygen | age -p > "$key" || rm -f "$key"
}

#
# Confirma una acción.
#
# @return boolean
#
confirm() {
  printf '%s [y/n]: ' "$1"

  #
  # Habilita la entrada sin formato,
  # stdin no espera un Return.
  #
  stty -icanon

  #
  # Lee un solo byte desde stdin.
  #
  answer=$(dd ibs=1 count=1 2>/dev/null)

  #
  # Habilita la entrada con formato.
  #
  stty icanon

  printf '\n'

  match "$answer" '[yY]'
}

#
# Lee una contraseña sin imprimirla.
#
pread() {
  printf '%s: ' "$2"

  stty -echo

  read -r "$1"

  stty echo

  printf '\n'
}

#
# Descifra un archivo con "age"
#
decrypt() { age -d -i "$key" "$1" || kill 0; }

#
# Obtiene la llave pública de cifrado.
#
pub() { decrypt "$key" | age-keygen -y; }

#
# Agrega una nueva contraseña.
#
add_pass() {
  [ -f "$fullname" ] &&
    errors "Pass name '$name' already exists"

  if confirm "Generate a random password?"; then
    #
    # Genera una contraseña aleatoria
    # desde una serie de bytes aleatorios.
    #
    pass=$(LC_ALL=C tr -dc "${PAGE_PATTERN:-_[:alnum:]}" < /dev/urandom |
         dd ibs=1 obs=1 count="${PAGE_LENGTH:-12}" 2>/dev/null)
  else
    pread pass "Enter password"

    pread pass2 "Enter password (again)"

    #
    # shellcheck disable=SC2154
    #
    [ "$pass" = "$pass2" ] || errors "Passwords don't match"
  fi

  [ -z "$pass" ] && errors "Failed to generate a password"

  pub=$(pub)

  match "$name" '*/*' && { mkdir -p "$categ" ||
    errors "Couldn't create category '$categ'"; }

  #
  # Utiliza "age" para almacenar una contraseña
  # dentro de un archivo cifrado.
  #
  age -r "$pub" -o "$fullname" <<-EOF &&
		$pass
	EOF

  printf '%s\n' "Saved '$name' to the store."
}

#
# Lista todas las contraseñas almacenadas.
#
list_pass() {
  find . -type f -name \*.age | sed 's/..//;s/\.age$//'
}

#
# Elimina contraseñas y categorías vacías.
#
delete_pass() {
  [ "$fullname" != "$key" ] &&
    confirm "Delete pass name '$name'?" && {
      rm -f "$fullname"

      rmdir -p "$categ" 2>/dev/null
  }
}

#
# Copia una contraseña al portapapeles.
#
copy_pass() {
  #
  # Herramienta de portapapeles por defecto.
  #
  : "${PAGE_CLIPBOARD:=waycopy -s seat0 -t text/plain}"

  decrypt "$fullname" | $PAGE_CLIPBOARD

  #
  # Ejecuta un proceso en segundo plano para limpiar
  # el portapapeles antes de un tiempo determinado.
  #
  [ "$PAGE_TIMEOUT" != off ] && {
    printf 'Clearing clipboard in "%s" seconds.\n' "${PAGE_TIMEOUT:=15}"

    sleep "$PAGE_TIMEOUT" || kill 0

    $PAGE_CLIPBOARD </dev/null
  } &
}

main() {
  command -v age 2>/dev/null >&2 ||
    errors "'age' not found"

  #
  # Ubicación de almacenamiento por defecto.
  #
  : "${PAGE_DIR:=${XDG_DATA_HOME:-$HOME/.local/share}/page}"

  mkdir -p "$PAGE_DIR" ||
    errors "Couldn't create password directory"

  cd "$PAGE_DIR" ||
    errors "Couldn't access password directory"

  action="$1"
  name="$2"
  fullname="$2".age
  categ=${2%/*}
  key=key.age

  match "$action" '-[acds]' && [ -z "$name" ] &&
    errors "Option $action requires an argument"

  match "$name" '*/*' && { match "$name" '*../*' ||
    match "$name" '*./*' &&
      errors "Category went out of bounds"; }

  match "$name" '/*' &&
    errors "Category can't start with '/'"

  match "$action" '-[cds]' && [ ! -f "$fullname" ] &&
    errors "Pass name '$name' doesn't exist"

  match "$action" '-[acds]' && [ ! -f "$key" ] &&
    errors "Couldn't find master key"

  #
  # Restringe los permisos de todos los archivos
  # generados solo al usuario actual: chmod 700
  #
  umask 077

  #
  # Asegura configurar la terminal a un estado
  # utilizable al finalizar el script o con Ctrl+C
  #
  [ -t 1 ] && trap 'stty echo icanon' INT EXIT

  case $action in
    -a) add_pass ;;
    -c) copy_pass ;;
    -d) delete_pass ;;
    -g) gen_key ;;
    -l) list_pass ;;
    -s) decrypt "$fullname" ;;
     *) shelp
  esac
}

#
# Desactiva siempre el modo debug.
#
set +x

#
# Desactiva la expansión de nombres de archivos para
# evitar inseguridades con la división de palabras.
#
set -f

main "$@"
